apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketdb
  template:
    metadata:
      labels:
        app: basketdb
    spec:
      containers:
      - name: basketdb
        image: localhost:5000/postgres
        imagePullPolicy: IfNotPresent
        resources:

        ports:
        - containerPort: 5433
        env:
        - name: POSTGRES_DB
          value: BasketDb
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
