apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributedcache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributedcache
  template:
    metadata:
      labels:
        app: distributedcache
    spec:
      containers:
      - name: distributedcache
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379