apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderdb
  template:
    metadata:
      labels:
        app: orderdb
    spec:
      containers:
      - name: orderdb
        image: mcr.microsoft.com/mssql/server
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 1434