apiVersion: apps/v1
kind: Deployment
metadata:
  name: yarpapigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarpapigateway
  template:
    metadata:
      labels:
        app: yarpapigateway
    spec:
      containers:
      - name: yarpapigateway
        image: yarpapigateway
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6004
